repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1  # Must be the same as in `pyproject.toml`.
    hooks:
      - id: isort
        # files: '(strava_client|tests)/'
        types: [file, python]
  - repo: https://github.com/python/black
    rev: 25.1.0  # Must be the same as in `pyproject.toml`.
    hooks:
      - id: black
        language_version: python3.13
        # files: '(strava_client|tests)/'
        types: [file, python]
